---
title: "plot GC over features of diff export"
author: "Uwe Schwartz"
date: "04/10/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
work.path<- "/Volumes/PromisePegasus/_Service_/S003_20210924_Export-AraThal/221130_pool_FC1_FC2/final2_GC_and_length/"
knitr::opts_knit$set(root.dir =work.path)
out.path<-paste0(work.path,"GC_plots/")
dir.create(out.path, recursive = T, showWarnings = F)
```


## Dependencies & Libraries

#### Load packages
```{r libraries, message=FALSE}
library(ggpubr)
```
## whole transcript
```{r exon}
### load output of bedtools nuc
cl1.exon.gc<-read.delim("GC/GC_content_exon_cl1.tsv")
cl2.exon.gc<-read.delim("GC/GC_content_exon_cl2.tsv")
noSig.exon.gc<-read.delim("GC/GC_content_exon_noSig.tsv")

getGCperFeature<-function(gc.table){
   gc.list<-split(gc.table, gc.table$X4_usercol)
   return(sapply(gc.list,function(x) sum(c(x$X10_num_C,x$X11_num_G))/sum(x$X15_seq_len))) 
}

cl1.gc<-getGCperFeature(cl1.exon.gc)
cl2.gc<-getGCperFeature(cl2.exon.gc)
noSig.gc<-getGCperFeature(noSig.exon.gc)

### median GC
#nuc enriched
median(cl1.gc)
#cyt enriched
median(cl2.gc)
#cyt enriched
median(noSig.gc)



df<-data.frame(
    GC_content=c(cl1.gc,cl2.gc, noSig.gc),
    cluster=factor(c(rep("enrichCyto",length(cl1.gc)),
                        rep("enrichNuc",length(cl2.gc)),
                        rep("not signif.",length(noSig.gc))),
                      levels=c("not signif.","enrichCyto","enrichNuc"))
)

p <- ggviolin(df, x = "cluster", y = "GC_content",
              color = "cluster", palette = c("#666666","#1B9E77","#D95F02"),
              add = "boxplot",
              title = "transcript")

my_comparisons <- list( c("not signif.","enrichCyto"), c("not signif.","enrichNuc") )
p.tx<-p + stat_compare_means(method = "t.test", comparisons = my_comparisons)

p.tx



```

## cds
```{r cds}
### load output of bedtools nuc
cl1.cds.gc<-read.delim("GC/GC_content_cds_cl1.tsv")
cl2.cds.gc<-read.delim("GC/GC_content_cds_cl2.tsv")
noSig.cds.gc<-read.delim("GC/GC_content_cds_noSig.tsv")


cl1.gc<-getGCperFeature(cl1.cds.gc)
cl2.gc<-getGCperFeature(cl2.cds.gc)
noSig.gc<-getGCperFeature(noSig.cds.gc)


### median GC
#nuc enriched
median(cl1.gc)
#cyt enriched
median(cl2.gc)
#cyt enriched
median(noSig.gc)

df<-data.frame(
    GC_content=c(cl1.gc,cl2.gc, noSig.gc),
    cluster=factor(c(rep("enrichCyto",length(cl1.gc)),
                        rep("enrichNuc",length(cl2.gc)),
                        rep("not signif.",length(noSig.gc))),
                      levels=c("not signif.","enrichCyto","enrichNuc"))
)

p <- ggviolin(df, x = "cluster", y = "GC_content",
              color = "cluster", palette = c("#666666","#1B9E77","#D95F02"),
              add = "boxplot",
              title = "cds")

my_comparisons <- list( c("not signif.","enrichCyto"), c("not signif.","enrichNuc") )
p.cds<-p + stat_compare_means(method = "t.test", comparisons = my_comparisons)

p.cds
```

```{r 3UTR}
### load output of bedtools nuc
cl1.UTR3.gc<-read.delim("GC/GC_content_UTR3_cl1.tsv")
cl2.UTR3.gc<-read.delim("GC/GC_content_UTR3_cl2.tsv")
noSig.UTR3.gc<-read.delim("GC/GC_content_UTR3_noSig.tsv")


cl1.gc<-getGCperFeature(cl1.UTR3.gc)
cl2.gc<-getGCperFeature(cl2.UTR3.gc)
noSig.gc<-getGCperFeature(noSig.UTR3.gc)

### median GC
#nuc enriched
median(cl1.gc)
#cyt enriched
median(cl2.gc)
#cyt enriched
median(noSig.gc)

df<-data.frame(
    GC_content=c(cl1.gc,cl2.gc, noSig.gc),
    cluster=factor(c(rep("enrichCyto",length(cl1.gc)),
                        rep("enrichNuc",length(cl2.gc)),
                        rep("not signif.",length(noSig.gc))),
                      levels=c("not signif.","enrichCyto","enrichNuc"))
)

p <- ggviolin(df, x = "cluster", y = "GC_content",
              color = "cluster", palette = c("#666666","#1B9E77","#D95F02"),
              add = "boxplot",
              title = "UTR3")

my_comparisons <- list( c("not signif.","enrichCyto"), c("not signif.","enrichNuc") )
p.UTR3<-p + stat_compare_means(method = "t.test", comparisons = my_comparisons)

p.UTR3
```

```{r 5UTR}
### load output of bedtools nuc
cl1.UTR5.gc<-read.delim("GC/GC_content_UTR5_cl1.tsv")
cl2.UTR5.gc<-read.delim("GC/GC_content_UTR5_cl2.tsv")
noSig.UTR5.gc<-read.delim("GC/GC_content_UTR5_noSig.tsv")


cl1.gc<-getGCperFeature(cl1.UTR5.gc)
cl2.gc<-getGCperFeature(cl2.UTR5.gc)
noSig.gc<-getGCperFeature(noSig.UTR5.gc)

### median GC
#nuc enriched
median(cl1.gc)
#cyt enriched
median(cl2.gc)
#cyt enriched
median(noSig.gc)

df<-data.frame(
    GC_content=c(cl1.gc,cl2.gc, noSig.gc),
    cluster=factor(c(rep("enrichCyto",length(cl1.gc)),
                        rep("enrichNuc",length(cl2.gc)),
                        rep("not signif.",length(noSig.gc))),
                      levels=c("not signif.","enrichCyto","enrichNuc"))
)

p <- ggviolin(df, x = "cluster", y = "GC_content",
              color = "cluster", palette = c("#666666","#1B9E77","#D95F02"),
              add = "boxplot",
              title = "UTR5")

my_comparisons <- list( c("not signif.","enrichCyto"), c("not signif.","enrichNuc") )
p.UTR5<-p + stat_compare_means(method = "t.test", comparisons = my_comparisons)

p.UTR5
```


```{r save tables, eval=FALSE, echo=FALSE }
pdf(paste0(out.path,"/GC_cds.pdf"), width=3.5, height = 4)
    print(p.cds)
dev.off()

pdf(paste0(out.path,"/GC_tx.pdf"), width=3.5, height = 4)
    print(p.tx)
dev.off()

pdf(paste0(out.path,"/GC_UTR3.pdf"), width=3.5, height = 4)
    print(p.UTR3)
dev.off()

pdf(paste0(out.path,"/GC_UTR5.pdf"), width=3.5, height = 4)
    print(p.UTR5)
dev.off()
```



##Session info
```{r info}
sessionInfo()


```